---
title: "SNPs and mutations nf-resolveome report"
author: "Alexandra Tidd"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    fig_width: 8
    keep_md: false
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 4
    theme: lumen
---

```{r setup, include = F, message = F, warning = F, echo = F}
# rmarkdown::render('reports/20250313_knit_nf-resolveome.Rmd', output_file = '220250313_knit_nf-resolveome.html', output_dir = 'reports/')

# chunk options
knitr::opts_chunk$set(warning = FALSE,
                      dpi = 300,
                      message = FALSE)
knitr::opts_knit$set(root.dir = "../")

# libraries
library(magrittr)
library(ggplot2)
```

### Load data

```{r load_data}
# get metadata
ss <-
  readr::read_csv("out/nf-resolveome/samplesheet.csv") %>%
  # we are interested in dna only for now
  dplyr::filter(seq_type == "dnahyb") %>%
  dplyr::mutate(
    out_dir = file.path("out/nf-resolveome", donor_id, seq_type, id),
    gene_covs = paste0(out_dir, "/genotyping/", id, "_gene_cov.tsv"),
    geno = paste0(out_dir, "/genotyping/", id, "_genotyped_mutations.tsv"),
    summary_txt = paste0(out_dir, "/mosdepth/", id, ".mosdepth.summary.txt"),
    global_txt = paste0(out_dir, "/mosdepth/", id, ".mosdepth.global.dist.txt"),
    regions_txt = paste0(out_dir, "/mosdepth/", id, ".mosdepth.region.dist.txt"))
my_params <-
  list(ids = ss$id, geno = ss$geno, summary_txt = ss$summary_txt, global_txt = ss$global_txt, regions_txt = ss$regions_txt)

# read files
dat <-
  list(#"geno" = list(file = my_params$geno, col_names = TRUE),
       "summary_txt" = list(file = my_params$summary_txt, col_names = TRUE),
       "global_txt" = list(file = my_params$global_txt, col_names = c("chr", "cov", "prop")),
       "regions_txt" = list(file = my_params$regions_txt, col_names = c("chr", "cov", "prop"))) %>%
  purrr::map(function(dat_i) {
    dat_i$file %>%
      purrr::map(readr::read_tsv, col_names = dat_i$col_names) %>%
      setNames(my_params$ids) %>%
      dplyr::bind_rows(.id = "id") %>%
      dplyr::rename_with(~ dplyr::if_else(. == "chrom", "chr", .), everything()) %>%
      dplyr::filter(!grepl("^GL", chr), !grepl("Un", chr),
                    !grepl("random|HLA", chr), !grepl("alt$", chr))
  })

# create a mutation source col if none present, split to list by source
if (!"source" %in% colnames(dat$geno)) {
  dat$geno$source <- "mutations"
}
dat$geno <- split(dat$geno, dat$geno$source)
```

### Coverage

```{r cov_mean}
dat$summary_txt %>%
  dplyr::filter(chr %in% c("total", "total_region")) %>%
  dplyr::mutate(lvl = ifelse(grepl("region$", chr), "region", "global"),
                chr = gsub("_.*", "", chr)) %>%
  ggplot(aes(x = reorder(id, -mean), y = mean, fill = lvl)) +
  geom_col(position = "dodge") +
  theme_minimal() +
  labs(title = "Mean coverage",
       x = "Plex",
       y = "Mean coverage") +
  theme(axis.text.x = element_text(angle = -90, hjust = 0))
```

```{r cov_dist}
dat[c("global_txt", "regions_txt")] %>%
  dplyr::bind_rows(.id = "lvl") %>%
  dplyr::filter(chr == "total", prop >= 0.01) %>%
  ggplot(aes(x = cov, y = prop, color = id, group = id)) +
  geom_line() +
  labs(title = paste("Coverage distribution"),
       x = "Coverage",
       y = "Proportion of bases at coverage") +
  theme_minimal() +
  facet_grid(~ lvl) +
  theme(legend.position = "none")
```

### VAF distribution

```{r vaf_dist}
# function: plot vaf distribution
plot_vaf_dist <- function(p_dat) {
  mut_depth_bins <- c("0", "1", ">1", ">5", ">10", ">50")
  p_dat2 <-
    p_dat %>%
    dplyr::mutate(mut_vaf = mut_depth / total_depth,
                  mut_depth_bin = dplyr::case_when(mut_depth > 50 ~ ">50",
                                                    mut_depth > 10 ~ ">10",
                                                    mut_depth > 5 ~ ">5",
                                                    mut_depth > 1 ~ ">1",
                                                    mut_depth == 1 ~ "1",
                                                    mut_depth == 0 ~ "0") %>%
                    factor(levels = mut_depth_bins))
  p_dat2 %>%
    ggplot(aes(x = mut_vaf, fill = mut_depth_bin, colour = mut_depth_bin)) +
    geom_histogram(bins = 100) +
    geom_vline(xintercept = median(p_dat2$mut_vaf, na.rm = TRUE),
               linetype = "dashed") +
    theme_minimal() +
    viridis::scale_fill_viridis(discrete = TRUE) +
    viridis::scale_color_viridis(discrete = TRUE)
}

# plot VAF distribution
purrr::walk2(names(dat$geno), dat$geno, function(p_source, p_dat) {
  # plot VAF distribution
  p <-
    p_dat %>%
    plot_vaf_dist() +
    ggtitle(paste(p_source, "- Distribution of VAFs"))
  print(p)

  # plot non-zero VAF distribution
  p <-
    p_dat %>%
    dplyr::filter(mut_depth > 0) %>%
    plot_vaf_dist() +
    ggtitle(paste(p_source, "- Distribution of non-zero VAFs"))
  print(p)

  # plot VAF distribution per id
  p <-
    p_dat %>%
    ggplot(aes(x = mut_vaf, colour = id)) +
    geom_density() +
    ggtitle(paste(p_source, "- Distribution of VAFs per cell")) +
    theme_minimal() +
    theme(legend.position = "none")
  print(p)

  # plot VAF distribution with increasing alt depth
  seq(1, 10) %>%
    purrr::walk(function(min_mut_depth) {
      p <-
        p_dat %>%
        dplyr::filter(mut_depth >= min_mut_depth) %>%
        plot_vaf_dist() +
        ggtitle(paste(p_source, "- Distribution of VAFs, min", min_mut_depth,
                      "alt depth"))
      print(p)
    })
})
```

### VAF heatmap

```{r vaf_heatmap, fig.width = 20, fig.height = 20}
# function: plot VAF heatmap
plot_vaf_heatmap <- function(p_dat, p_source) {

  # prepare data
  p_dat2 <-
    p_dat %>%
    dplyr::mutate(mut_id = paste(chr, pos, ref, alt, sep = "_")) %>%
    # count number of cells with each mutation
    dplyr::add_count(mut_id, name = "n_cells_w_mut")

  # reshape data for heatmap
  heatmap_data <-
    p_dat2 %>%
    reshape2::dcast(mut_id + n_cells_w_mut ~ id, value.var = "mut_vaf")
  rownames(heatmap_data) <- heatmap_data$mut_id
  heatmap_matrix <- as.matrix(heatmap_data[, -c(1:3)]) # drop annotations
  n_total_muts <- dplyr::n_distinct(p_dat2$mut_id)
  n_total_cells <- dplyr::n_distinct(p_dat2$id)

  # calculate the number of mutations per column (id)
  annotation_col <-
    p_dat2 %>%
    dplyr::count(id, name = "n_muts") %>%
    tibble::column_to_rownames("id")

  # replace NAs with 0 
  heatmap_matrix[is.na(heatmap_matrix)] <- 0

  # prepare annotations for columns
  annotation_row <- data.frame(n_cells_w_mut = heatmap_data$n_cells_w_mut)
  rownames(annotation_row) <- heatmap_data$mut_id

  # plot
  pheatmap::pheatmap(
    mat = heatmap_matrix,
    cluster_rows = TRUE,
    cluster_cols = TRUE,
    annotation_row = annotation_row,
    annotation_col = annotation_col,
    color = colorRampPalette(c("white", "blue"))(50),
    main = paste(p_source, "- VAF heatmap\n",
                 n_total_cells, "cells,", n_total_muts, "mutations")
  )
}

# plot
purrr::walk2(names(dat$geno), dat$geno, function(p_source, p_dat) {
  p <-
    p_dat %>%
    dplyr::filter(mut_depth > 5, mut_vaf > 0.1) %>%
    plot_vaf_heatmap(p_source)
  print(p)
  p <-
    p_dat %>%
    dplyr::filter(mut_depth > 5, mut_vaf > 0.1, !is.na(gene)) %>%
    plot_vaf_heatmap(paste(p_source, "(coding muts only)"))
  print(p)
})
```

### VAF distribution across chromosomes

```{r chr_vaf_dist, fig.width = 15, fig.height = 4}
purrr::walk2(names(dat$geno), dat$geno, function(p_source, p_dat) {
  p_dat_by_id <- split(p_dat, p_dat$id)
  purrr::walk2(names(p_dat_by_id), p_dat_by_id, function(p_id, p_dat2) {
    p <-
      p_dat2 %>%
      dplyr::select(id, chr, pos, mut_vaf) %>%
      dplyr::mutate(mut_baf = 1 - mut_vaf,
                    chr = factor(sub("^chr", "", chr), levels = c(as.character(1:22), "X", "Y"))) %>%
      dplyr::arrange(chr, pos) %>%
      dplyr::group_by(chr) %>%
      dplyr::mutate(chr_alternating = dplyr::cur_group_id() %% 2,
                    min_pos = min(pos), max_pos = max(pos)) %>%
      tidyr::pivot_longer(cols = c("mut_vaf", "mut_baf"), names_to = "vaf_type") %>%
      ggplot(aes(x = pos, y = value)) +
      geom_rect(aes(ymin = 0, ymax = 1, xmin = min_pos, xmax = max_pos,
                    fill = as.factor(chr_alternating))) +
      geom_hline(yintercept = 0.5, colour = "red") +
      geom_point(size = 0.5) +
      scale_x_continuous(expand = c(0, 0)) +
      scale_fill_manual(values = c("lightgrey", "white")) +
      ggh4x::facet_grid2(id ~ chr, scales = "free_x", space = "free_x") +
      theme_classic() +
      theme(panel.spacing = unit(0, "lines"),
            panel.border = element_rect(color = "grey", fill = NA,
                                        linewidth = 0),
            strip.background = element_rect(color = "grey", fill = NA,
                                            linewidth = 0, linetype = "solid"),
            axis.text.x = element_blank(), axis.ticks.x = element_blank(),
            legend.position = "none") +
      ggtitle(paste(p_source, "-", p_id, "- VAF distribution across chromosomes"))
    print(p)
  })
})
```

### Gene coverage

```{r gene_cov, fig.height = 20}
gene_covs <-
  my_params$gene_covs %>%
  purrr::map(function(file) {
    p_dat <-
      file %>%
      readr::read_tsv(col_types = list("chr" = readr::col_character())) %>%
      dplyr::mutate(start2 = start, end2 = end) %>%
      dplyr::group_by(chr, gene, cov, id, start, end) %>%
      dplyr::reframe(pos = start2:end2)
  }) %>%
  dplyr::bind_rows() %>%
  {split(., .$gene)}

purrr::map2(names(gene_covs), gene_covs, function(p_gene, p_dat) {
  p_dat %>%
    ggplot(aes(x = pos, y = cov)) +
    geom_area() +
    facet_grid(id ~ .) +
    ggtitle(paste(p_gene, "coverage")) +
    theme_minimal()
})
```